version: '3'

services:
    shardbase:
        build:
            dockerfile: ./docker/shard/Dockerfile
            context: .
    spqrbase:
        build:
            dockerfile: ./docker/spqr/Dockerfile
            context: .
    shard1:
        image:
            spqr_shardbase
        environment:
            PG_LISTEN_ADDR: "${PG_LISTEN_ADDR:-spqr_shard1_1.spqr_spqr.}"
        ports:
            - "7432:6432"
        hostname: spqr_shard_1_1
        networks:
            spqr:
                ipv4_address: 192.168.233.03
    shard2:
        image:
            spqr_shardbase
        environment:
            PG_LISTEN_ADDR: "${PG_LISTEN_ADDR:-spqr_shard2_1.spqr_spqr.}"
        ports:
            - "7433:6432"
        hostname: spqr_shard_2_1
        networks:
            spqr:
                ipv4_address: 192.168.233.02
    coordinator:
        build:
            dockerfile: ./docker/coordinator/Dockerfile
            context: .
        ports:
            - "7002:7002"
            - "7003:7003"
        hostname: spqr_coordinator
        networks:
            spqr:
                ipv4_address: 192.168.233.07
    world1:
        image:
            spqr_shardbase
#        build:
#            dockerfile: ./docker/world/Dockerfile
#            context: .
        environment:
            PG_LISTEN_ADDR: "${PG_LISTEN_ADDR:-spqr_world1_1.spqr_spqr.}"
        hostname: spqr_world_0_1
        ports:
            - "7434:6432"
        networks:
            spqr:
                ipv4_address: 192.168.233.08
    qdb01:
        image: 'bitnami/etcd:latest'
        hostname: spqr_qdb_0_1
        environment:
            ALLOW_NONE_AUTHENTICATION: "yes"
            ETCD_LOG_LEVEL: "debug"
        networks:
            spqr:
                ipv4_address: 192.168.233.06
    router:
        build:
            dockerfile: ./docker/router/Dockerfile
            context: .
        ports:
            - "8432:6432"
        hostname: spqr_router_1_1
        networks:
            spqr:
                ipv4_address: 192.168.233.04
    client:
        build:
            dockerfile: ./docker/tests/Dockerfile
            context: .
        hostname: spqr_client
        networks:
            spqr:
                ipv4_address: 192.168.233.05

networks:
    spqr:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.233.0/24
